### ISSUE TITLE
Add Typescript Declaration

### ISSUE THREAD

**Issue by danilotorrisi** [onezerobinary/symbol-cli-wallet#1]
Wouldn't be cool if *someone* adds the typescript declaration to the package.json?

**Comment by onezerobinary** [comment]
Thank you for the suggestion @danilotorrisi.
I've added the typescript declaration  and updated the repo. Let me know if I could close the issue.

**Comment by onezerobinary** [comment]
I think that now the repo is well updated. Thank's again for your commitment.
